export const USER_DETAILS_ADDED = 'WORKER_DETAILS_ADDED';

export const MAIN_SCREEN_ITEMS_LOADING = 'MAIN_SCREEN_ITEMS_LOADING';
export const MAIN_SCREEN_ITEMS_SUCCESS = 'MAIN_SCREEN_ITEMS_SUCCESS';
export const MAIN_SCREEN_ITEMS_EMPTY_SUCCESS = 'MAIN_SCREEN_ITEMS_EMPTY_SUCCESS';
export const MAIN_SCREEN_ITEMS_ERROR = 'MAIN_SCREEN_ITEMS_ERROR';

export const ACCESS_TOKEN_LOADED = 'ACCESS_TOKEN_LOADED';
export const AUTH_TOKEN_LOADED = 'AUTH_TOKEN_LOADED';
export const CODE_LOADED = 'CODE_LOADED';


export const FIRST_SCREEN_EMAIL_EDITED = 'FIRST_SCREEN_EMAIL_EDITED';
export const FIRST_SCREEN_PASSWORD_EDITED = 'FIRST_SCREEN_PASSWORD_EDITED';
export const FIRST_SCREEN_PURGED = 'FIRST_SCREEN_PURGED';

export const FIRST_SCREEN_CHANGE_PAGE = 'FIRST_SCREEN_CHANGE_PAGE';

export const MAIN_SCREEN_BTC_DETAILS = 'MAIN_SCREEN_BTC_DETAILS';

export const ITEM_READ = 'ITEM_READ';
export const ITEM_LOADED = 'ITEM_LOADED';
export const ITEM_ACCEPT = 'ITEM_ACCEPT';
export const ITEM_DECLINED = 'ITEM_DECLINED';
export const ITEM_STOPPED = 'ITEM_STOPPED';
